name: CI
on: [ push, pull_request ]
jobs:
  build-ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
      - uses: actions/checkout@v2
      - name: build & run
        run: |
          sudo apt install ninja-build cmake
          mkdir build
          cmake -G Ninja -B build/
          cmake --build build
          cd build
          ctest

  build-macos:
    name: macos
    runs-on: macos-latest
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v2
      - name: build & run
        run: |
          brew install ninja
          mkdir build
          cmake -G Ninja -B build/
          cmake --build build
          cd build
          ctest
  
  build-windows:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: build / run
        run: |
          choco install ninja
          mkdir build
          cmake -G Ninja -B build/
          cmake --build build
          cd build
          ctest