name: CI
on: [ push, pull_request ]
jobs:
  build-ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
      - uses: actions/checkout@v2
      - name: build & run
        run: |
          sudo apt install ninja-build cmake
          mkdir build
          cmake -G Ninja -B build/
          cmake --build build
          build/forkmem-test
